repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
          "-rn", # Only display messages
          "-sn", # Do not display the score
          "--rcfile=.pylintrc", # Link to your config file
          "--load-plugins=pylint.extensions.docparams", # Load the docparams plugin
          ]